import './globals.css'
import Link from 'next/link';

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>  
                <div className="navbar">
                    <Link href="/">홈</Link>
                    <Link href="/signup">회원가입</Link>
                    <Link href="/login">로그인</Link>
                </div>
                {children}
            </body>
        </html>
    );
}
