"use client";

import "../globals.css";
import Link from "next/link";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <html lang="en">
            <body>
                <div className="navbar">
                    <Link href="/">홈</Link>
                    <Link href="/main/dashboard">대시보드</Link>
                    <Link href="/login">휴가 신청</Link>

                </div>
                {children}
            </body>
        </html>
    );
};

export default RootLayout;
